New way for search result pagination
lucnascimento98/ASP.NET-WebAPI pull request #15
Opened 2022-02-15 01:18 UTC by lucnascimento98

2022-02-15 14:14 UTC, patrickhacens requested changes

2022-02-15 14:14 UTC, patrickhacens commented on ContosoPizza/ContosoPizza.csproj
> +    <PackageReference Include="Nudes.Paginator.Core" Version="1.0.494" />
Nudes.Paginator já inclui o Nudes.Paginator.Core, você pode remover essa linha

2022-02-15 14:14 UTC, patrickhacens commented on ContosoPizza/Features/Pizzas/GetAll/GetAllPizzaHandler.cs
> +            return await pizzas.Select(p => new PizzaDTO()
Se você der um return await aqui vc não precisa que o método seja async, estou dizendo isso mas vc vai precisar que o método seja async no final

2022-02-15 14:14 UTC, patrickhacens commented on ContosoPizza/Features/Pizzas/GetAll/GetAllPizzaHandler.cs
> +            }).PaginateBy(new PageRequest()
PageRequest não deve ser criado, a sua Request deverá herdar de PageRequest para que o usuário possa passar Page, PageSize etc,
Toda requisição paginada deverá herdar, ai você usaria `.PaginateBy(request)`

2022-02-15 14:14 UTC, patrickhacens commented on ContosoPizza/Features/Pizzas/GetAll/GetAllPizzaHandler.cs
> -            return pizzasDTO;
Toda requisição Paginada precisa retornar dados de paginação especifico (pagina, total etc) para fazer isso você deverá retornar PagedResult<T> então sua request deverá herdar `PageRequest` e implantar `IRequest<PagedResult<T>>`

2022-02-15 14:14 UTC, patrickhacens commented on ContosoPizza/Features/Toppings/GetAll/GetAllToppingHandler.cs
> +            }).PaginateBy(new PageRequest()
mesmos pontos que o da pizza

2022-02-15 14:18 UTC, lucnascimento98 commented on ContosoPizza/ContosoPizza.csproj
> +    <PackageReference Include="Nudes.Paginator.Core" Version="1.0.494" />
ok

2022-02-15 15:36 UTC, lucnascimento98 commented on ContosoPizza/Features/Pizzas/GetAll/GetAllPizzaHandler.cs
> +            return await pizzas.Select(p => new PizzaDTO()
ok

2022-02-15 15:40 UTC, lucnascimento98 commented on ContosoPizza/Features/Pizzas/GetAll/GetAllPizzaHandler.cs
> +            }).PaginateBy(new PageRequest()
ok

2022-02-15 15:41 UTC, lucnascimento98 commented on ContosoPizza/Features/Pizzas/GetAll/GetAllPizzaHandler.cs
> -            return pizzasDTO;
ok

2022-02-15 16:01 UTC, lucnascimento98 commented on ContosoPizza/Features/Toppings/GetAll/GetAllToppingHandler.cs
> +            }).PaginateBy(new PageRequest()
ok

2022-02-15 19:56 UTC, patrickhacens requested changes

2022-02-15 19:56 UTC, patrickhacens commented on ContosoPizza/Features/Pizzas/GetAll/GetAllPizzaHandler.cs
> +            return new PageResult<PizzaDTO>(list);
Não funciona, acesse o endpoint pelo swagger e veja que a paginação não mostra a quantidade total de itens/paginas
RTFM

2022-02-15 19:56 UTC, patrickhacens commented on ContosoPizza/Features/Toppings/GetAll/GetAllToppingHandler.cs
> +    public class GetAllToppingHandler :PageRequest, IRequestHandler<GetAllToppingRequest, PageResult<ToppingDTO>>
O `Handler` não herda de `PageRequest` quem herda é a `Request` nesse caso `GetAllToppingRequest`

2022-02-15 19:56 UTC, patrickhacens commented on ContosoPizza/Features/Toppings/GetAll/GetAllToppingHandler.cs
> +            return new PageResult<ToppingDTO>(list);
Não funciona, vide comentário acima
RTFM

2022-02-15 20:45 UTC, lucnascimento98 commented on ContosoPizza/Features/Toppings/GetAll/GetAllToppingHandler.cs
> +    public class GetAllToppingHandler :PageRequest, IRequestHandler<GetAllToppingRequest, PageResult<ToppingDTO>>
ok

2022-02-15 20:50 UTC, lucnascimento98 commented on ContosoPizza/Features/Pizzas/GetAll/GetAllPizzaHandler.cs
> +            return new PageResult<PizzaDTO>(list);
ok

2022-02-15 20:50 UTC, lucnascimento98 commented on ContosoPizza/Features/Toppings/GetAll/GetAllToppingHandler.cs
> +            return new PageResult<ToppingDTO>(list);
ok

2022-02-15 20:54 UTC, patrickhacens requested changes

2022-02-15 20:54 UTC, patrickhacens commented on ContosoPizza/Features/Pizzas/GetAll/GetAllPizzaHandler.cs
> +            var total = list.Count;
Testa.

2022-02-15 20:55 UTC, lucnascimento98 commented on ContosoPizza/Features/Pizzas/GetAll/GetAllPizzaHandler.cs
> +            var total = list.Count;
Eu testei.

2022-02-15 21:56 UTC, patrickhacens requested changes

2022-02-15 21:56 UTC, patrickhacens commented on ContosoPizza/Features/Pizzas/GetAll/GetAllPizzaHandler.cs
> +            var total = await pizzas.CountAsync();
falta cancellation token

2022-02-15 21:56 UTC, patrickhacens commented on ContosoPizza/Features/Toppings/GetAll/GetAllToppingHandler.cs
> +            var total = await toppings.CountAsync();
cancellationToken

2022-02-16 13:05 UTC, patrickhacens approved these changes

2022-02-16 13:05 UTC, merged