Endpoints for user sign up and authentication
lucnascimento98/ASP.NET-WebAPI pull request #18
Opened 2022-02-19 18:40 UTC by lucnascimento98

2022-02-19 18:55 UTC, patrickhacens requested changes
Dito os pontos que revi, o CRUD de role não influencia nada nem no cadastro nem na autenticação

2022-02-19 18:55 UTC, patrickhacens commented on ContosoPizza/Features/Roles/GetAll/GetAllRoleHandler.cs
> +            var roles = db.Roles.Select(roles => roles);
.select(d => d) faz nada, se você quer definir uma consulta em cima disso use .AsQueryable

2022-02-19 18:55 UTC, patrickhacens commented on ContosoPizza/Features/Roles/RolesController.cs
> +            return _mediator.Send(request, cancellationToken);
pq aqui é request no lugar de addRoleRequest?
eu sei que não faz diferença no código, porém você usou um padrão em todos os outros endpoints exceto nesse

2022-02-21 14:49 UTC, patrickhacens requested changes

2022-02-21 14:49 UTC, patrickhacens commented on ContosoPizza/Features/Users/Add/AddUserHandler.cs
> +            if (!db.Roles.Any(role => role.Id == request.RoleId))
falta asyncronia e cancellation token

2022-02-21 14:49 UTC, patrickhacens commented on ContosoPizza/Features/Users/Add/AddUserRequest.cs
> +        public int RoleId { get; set; }
Num cadastro publico de usuário o Role não deverá ser passado, porém no cadastro interno de usuário o Role poderá ser passado

2022-02-21 14:49 UTC, patrickhacens commented on ContosoPizza/Program.cs
> +builder.Services.AddSingleton(typeof(TokenService));
vc pode usar `builder.Services.AddSingleton<TokenService>()`

2022-02-21 14:49 UTC, patrickhacens commented on ContosoPizza/Program.cs
> +var key = Encoding.ASCII.GetBytes(builder.Configuration.GetSection("Authentication").GetValue(typeof(string), "SecretString").ToString());
Chama de JWTKey no lugar de SecretString

2022-02-21 14:49 UTC, patrickhacens commented on ContosoPizza/appsettings.json
> +    "SecretString": "fedaf7d8863b48e197b9287d492b708e"
senhas, segredos e outros mais não devem ficar no github! ainda mais em um repo publico

2022-02-21 14:49 UTC, patrickhacens commented on ContosoPizza/Services/TokenService.cs
> +            var key = Encoding.ASCII.GetBytes(_configuration.GetSection("Authentication").GetValue(typeof(string), "SecretString").ToString());
GetValue pode ser usado com GetValue<string>("name")

2022-02-21 14:49 UTC, patrickhacens commented on ContosoPizza/Features/Users/Update/UpdateUserHandler.cs
> +            user.PasswordHash = BCrypt.Net.BCrypt.HashPassword(request.User.Password);
a requisição de alteração de usuário não deverá alterar o password, deverá haver um endpoint separado para fazer o update do password que deverá validar o password antigo

2022-02-21 14:54 UTC, lucnascimento98 commented on ContosoPizza/Features/Users/Add/AddUserHandler.cs
> +            if (!db.Roles.Any(role => role.Id == request.RoleId))
ok

2022-02-21 14:56 UTC, lucnascimento98 commented on ContosoPizza/Program.cs
> +builder.Services.AddSingleton(typeof(TokenService));
ok

2022-02-21 15:03 UTC, lucnascimento98 commented on ContosoPizza/Services/TokenService.cs
> +            var key = Encoding.ASCII.GetBytes(_configuration.GetSection("Authentication").GetValue(typeof(string), "SecretString").ToString());
ok

2022-02-21 17:27 UTC, lucnascimento98 commented on ContosoPizza/Features/Users/Update/UpdateUserHandler.cs
> +            user.PasswordHash = BCrypt.Net.BCrypt.HashPassword(request.User.Password);
ok

2022-02-22 12:34 UTC, lucnascimento98 commented on ContosoPizza/appsettings.json
> +    "SecretString": "fedaf7d8863b48e197b9287d492b708e"
ok

2022-02-22 19:56 UTC, patrickhacens requested changes

2022-02-22 19:56 UTC, patrickhacens commented on ContosoPizza/Features/Users/Add/AddUserHandler.cs
> +            var UserContext = httpContextAccessor.HttpContext.User;
variaveis devem ter o nome em minusculo

2022-02-22 19:56 UTC, patrickhacens commented on ContosoPizza/Features/Users/Add/AddUserHandler.cs
> +            var idCliente = (await db.Roles.FirstOrDefaultAsync(d => d.Name == "cliente", cancellationToken)).Id;
padrão de nomenclatura de variavel tem sido entityId e não idEntity

2022-02-22 19:56 UTC, patrickhacens commented on ContosoPizza/Features/Users/Add/AddUserHandler.cs
> +                return new BadRequestError();
Erro deverá ser NotFound, neste caso seria importante também apontar qual propriedade da request causou o erro usando `return new NotFoundError().AddFieldErrors(nameof(request.RoleId), "NotFound")`

2022-02-22 19:56 UTC, patrickhacens commented on ContosoPizza/Features/Users/Add/AddUserHandler.cs
> +            if (roleId == null || roleId.Value == idCliente.ToString()) //se o usuaro for anonimo ou um cliente
se role Id for nulo nós carregamos já o id do role "cliente" isso é performático apesar de funcionar.
Basear-se com o Role em texto hardcoded também é um ponto ruim

porém o pior mesmo é que se adicionarmos um novo role que não deveria ter essa permissão e esse role faz o cadastro nós passariamos. A verificação deveria ser `se o usuário for um funcionário` e não `se o usuário não for um cliente`

2022-02-22 19:56 UTC, patrickhacens commented on ContosoPizza/Features/Users/Add/AddUserHandler.cs
> +                    return new UnauthorizedError();
Unauthorized é o erro quando o usuário não está logado, para erros quando o usuário está logado mas não pode acessar um recurso o erro é Forbidden

2022-02-22 19:56 UTC, patrickhacens commented on ContosoPizza/Features/Users/ChangePasswod/ChangePasswordRequest.cs
> +        public int Id { get; set; }
Você não deveria receber o Id do usuário
se eu estiver logado na plataforma e souber o Id do seu usuário eu conseguiria chamar essa requisição para alterar a sua senha.

O ideal é pegar o usuário através do mesmo mecanismo do Role (ClaimsPrincipal IdentityPrincipal algo parecido)

2022-02-22 19:56 UTC, patrickhacens commented on ContosoPizza/Features/Users/ChangePasswod/ChangePasswordHandler.cs
> +                return new BadRequestError();
Se o seu usuário estiver logado mas vc não está achando ele no banco, não é um erro de cliente (BadRequest) é um erro interno do servidor, mais conhecido como o `servidor faz a menor ideia do que ta acontecendo e como as coisas poderiam chegar nesse ponto`

2022-02-22 19:56 UTC, patrickhacens commented on ContosoPizza/Features/Users/Update/UpdateUserHandler.cs
> +            user.PasswordHash = BCrypt.Net.BCrypt.HashPassword(request.User.Password);
vc deu ok aqui mas e colocou a discussão como resolved mas o código ainda continua sem estar resolvido

2022-02-22 19:56 UTC, patrickhacens commented on ContosoPizza/appsettings.Development.json
> -{
Por que o arquivo foi excluido?

2022-02-22 19:56 UTC, patrickhacens commented on ContosoPizza/appsettings.json
> -{
Por que o arquivo foi excluido?

2022-02-22 20:00 UTC, lucnascimento98 commented on ContosoPizza/Features/Users/Add/AddUserHandler.cs
> +            var UserContext = httpContextAccessor.HttpContext.User;
ok

2022-02-22 20:01 UTC, lucnascimento98 commented on ContosoPizza/Features/Users/Add/AddUserHandler.cs
> +            var idCliente = (await db.Roles.FirstOrDefaultAsync(d => d.Name == "cliente", cancellationToken)).Id;
ok

2022-02-22 20:03 UTC, lucnascimento98 commented on ContosoPizza/Features/Users/Add/AddUserHandler.cs
> +                return new BadRequestError();
ok

2022-02-22 20:17 UTC, lucnascimento98 commented on ContosoPizza/Features/Users/Add/AddUserHandler.cs
> +                    return new UnauthorizedError();
ok

2022-02-22 20:54 UTC, lucnascimento98 commented on ContosoPizza/Features/Users/ChangePasswod/ChangePasswordHandler.cs
> +                return new BadRequestError();
kkkkkkkkkkkkkkkkkk
ok

2022-02-23 19:56 UTC, patrickhacens requested changes

2022-02-23 19:56 UTC, patrickhacens commented on ContosoPizza/Features/Authentication/AuthentictionController.cs
> +    public class AuthentictionController : ControllerBase
Typo

2022-02-23 19:56 UTC, patrickhacens commented on ContosoPizza/Features/Authentication/AuthentictionController.cs
> +        public Task<ResultOf<AuthenticationResult>> Create([FromBody] LoginRequest loginRequest, CancellationToken cancellationToken)
Você não está criando nada, essa requisição é um login, trocar o nome do método

2022-02-23 19:56 UTC, patrickhacens commented on ContosoPizza/Features/Users/ChangePasswod/ChangePasswordRequestValidator.cs
> +        }
Aqui não deveria ter a mesma regra para o OldPassword?

2022-02-23 19:56 UTC, patrickhacens commented on ContosoPizza/Features/Users/Update/UpdateUserRequestValidator.cs
> +                .WithMessage("Email not valid.");
O FluentValidator tem mensagens padrões, se não me engano essa mensagem seria para caso o email estiver vazio, vc pode remover o `WithMessage()` para usar as mensagens padrões

2022-02-24 12:32 UTC, lucnascimento98 commented on ContosoPizza/Features/Users/Update/UpdateUserRequestValidator.cs
> +                .WithMessage("Email not valid.");
ok

2022-02-24 12:33 UTC, lucnascimento98 commented on ContosoPizza/Features/Authentication/AuthentictionController.cs
> +        public Task<ResultOf<AuthenticationResult>> Create([FromBody] LoginRequest loginRequest, CancellationToken cancellationToken)
ok

2022-02-24 12:46 UTC, lucnascimento98 commented on ContosoPizza/Features/Users/ChangePasswod/ChangePasswordRequestValidator.cs
> +        }
nao coloquei a regra pra OldPassword pq ja existe essa verificação da senha na criação do usuario, e na troca de senha há uma verificação pra ver se oldPassword está igual ao password cadastrado

2022-02-24 13:46 UTC, patrickhacens approved these changes

2022-02-24 13:47 UTC, merged