Implementing MediatR
lucnascimento98/ASP.NET-WebAPI pull request #2
Opened 2022-01-27 16:39 UTC by lucnascimento98

2022-01-27 16:51 UTC, patrickhacens requested changes
Verifica os pontos e caso tiver duvida me chama no discord

2022-01-27 16:51 UTC, patrickhacens commented on ContosoPizza/Features/Pizzas/PizzaController.cs
> +            GetAllPizzaRequest getAllPizzaRequest = new()
Se todas as propriedades de uma request tiverem a mesma origem ([FromQuery]) vc pode mapear a request como parametro da action no lugar de mapear cada propriedade

2022-01-27 16:51 UTC, patrickhacens commented on ContosoPizza/Features/Pizzas/PizzaController.cs
> +        public async Task<ActionResult<Pizza>> Get(int id, CancellationToken cancellationToken)
vc testou isso aqui?

2022-01-27 16:51 UTC, patrickhacens commented on ContosoPizza/Features/Toppings/Get/GetToppingHandler.cs
> +            return await db.Toppings.FirstOrDefaultAsync(p => p.Id == request.Id, cancellationToken);
await é desnecessário aqui

2022-01-27 16:51 UTC, patrickhacens commented on ContosoPizza/Features/Toppings/ToppingController.cs
> +            GetAllToppingRequest getAllToppingRequest = new()
Quando todos os items de uma request tiver a mesma origem vc pode mapear a request inteira

2022-01-27 16:51 UTC, patrickhacens commented on ContosoPizza/Features/Toppings/ToppingController.cs
> +            GetToppingRequest getToppingRequest = new()
Quando todos os items de uma request tiver a mesma origem vc pode mapear a request inteira

2022-01-27 16:51 UTC, patrickhacens commented on ContosoPizza/Features/Toppings/ToppingController.cs
> +        public async Task<IActionResult> Delete(int id, CancellationToken cancellationToken)
Quando todos os items de uma request tiver a mesma origem vc pode mapear a request inteira

2022-01-27 16:55 UTC, lucnascimento98 commented on ContosoPizza/Features/Pizzas/PizzaController.cs
> +        public async Task<ActionResult<Pizza>> Get(int id, CancellationToken cancellationToken)
Sim, ta funcionando normal

2022-01-27 17:22 UTC, patrickhacens requested changes
Tem mais dois métodos que tem o async desnecessários arruma isso que vem o approve

2022-01-27 17:22 UTC, patrickhacens commented on ContosoPizza/Features/Pizzas/GetAll/GetAllPizzaHandler.cs
> +        public async Task<List<Pizza>> Handle(GetAllPizzaRequest request, CancellationToken cancellationToken)
Esse método também n precisa do async

2022-01-27 17:22 UTC, patrickhacens commented on ContosoPizza/Features/Toppings/GetAll/GetAllToppingHandler.cs
> +        public async Task<List<Topping>> Handle(GetAllToppingRequest request, CancellationToken cancellationToken)
Esse método também não precisa do async

2022-01-27 17:30 UTC, patrickhacens requested changes

2022-01-27 17:30 UTC, patrickhacens commented on ContosoPizza/Features/Pizzas/PizzaController.cs
> +        public async Task<ActionResult<Pizza>> Get(GetPizzaRequest getPizzaRequest, CancellationToken cancellationToken)
Não funciona, testa novamente e corrige

2022-01-27 17:56 UTC, patrickhacens requested changes
Esse ultimo commit até resolve o problema, porem a API fica com uma pior experiencia de usuário, favor reverter esse comit

2022-02-01 20:21 UTC, patrickhacens approved these changes

2022-02-01 20:22 UTC, merged