Using DTOs
lucnascimento98/ASP.NET-WebAPI pull request #8
Opened 2022-02-09 13:41 UTC by lucnascimento98

2022-02-09 21:01 UTC, patrickhacens requested changes

2022-02-09 21:01 UTC, patrickhacens commented on ContosoPizza/models/Topping.cs
> +    public class ToppingDTO
Os DTOs devem ficar em um arquivo separado de preferencia em uma pasta separada das models

2022-02-09 21:01 UTC, patrickhacens commented on ContosoPizza/models/Pizza.cs
> +    public class PizzaDTO
Os DTOs devem ficar em um arquivo separado de preferencia em uma pasta separada das models

2022-02-09 21:01 UTC, patrickhacens commented on ContosoPizza/Features/Toppings/Update/UpdateToppingRequest.cs
> +    public class UpdateToppingRequestDTO
Os DTOs devem ficar em um arquivo separado de preferencia em uma pasta separada das models

2022-02-09 21:01 UTC, patrickhacens commented on ContosoPizza/Features/Toppings/GetAll/GetAllToppingHandler.cs
> +            foreach (var topping in await toppings.ToListAsync(cancellationToken))
Você pode fazer uma projeção direto no banco antes de trazer os dados eg
```csharp
toppings.Select(d=> new ToppingDTO(){ /* sets */ }).ToListAsync(cancellationToken)
```

2022-02-09 21:01 UTC, patrickhacens commented on ContosoPizza/Features/Pizzas/PizzaController.cs
> +                Id = id,
Aqui você pode receber o proprio UpdatePizzaRequest ao invez de ter da DTO e criar o UpdatePizzaRequest.
O problema inicial era que vc tinha seu domain (Pizza) como propriedade da request, mas como não faz mais parte você pode receber ela

2022-02-11 14:06 UTC, lucnascimento98 commented on ContosoPizza/Features/Pizzas/PizzaController.cs
> +                Id = id,
Se eu nao usar esse DTO pro request, o id vai ser solicitado no route e no body, mesmo que o do body seja ignorado.
Criei esse DTO pra nao ser necessario passar o ID no body tambem, isso nao estaria certo?

2022-02-11 14:13 UTC, lucnascimento98 commented on ContosoPizza/models/Topping.cs
> +    public class ToppingDTO
ok

2022-02-11 14:13 UTC, lucnascimento98 commented on ContosoPizza/models/Pizza.cs
> +    public class PizzaDTO
ok

2022-02-11 15:35 UTC, lucnascimento98 commented on ContosoPizza/Features/Toppings/GetAll/GetAllToppingHandler.cs
> +            foreach (var topping in await toppings.ToListAsync(cancellationToken))
ok

2022-02-11 17:46 UTC, patrickhacens commented on ContosoPizza/Features/Pizzas/PizzaController.cs
> +                Id = id,
Duas coisas que são diferentes ta
Uma delas é a documentação SWAGGER que é gerada automaticamente
outra é o que de facto sua API aceita
a doc do swagger tem uns limites pro auto gerado e sempre devemos se preucupar mais com o de facto que a doc, a doc é importante mas temos que analisar o trabalho versus o beneficio.

Há algumas formas de evitar isso mudando suas requests, porém vc está duplicando os campos referente a pizza e passando eles para a request, quando vc poderia passar a DTO inteira

2022-02-11 18:31 UTC, lucnascimento98 commented on ContosoPizza/Features/Toppings/Update/UpdateToppingRequest.cs
> +    public class UpdateToppingRequestDTO
ok

2022-02-11 18:31 UTC, lucnascimento98 commented on ContosoPizza/Features/Pizzas/PizzaController.cs
> +                Id = id,
ok

2022-02-11 20:23 UTC, patrickhacens requested changes

2022-02-11 20:23 UTC, patrickhacens commented on ContosoPizza/Features/Pizzas/GetAll/GetAllPizzaHandler.cs
> +            foreach (var pizza in await pizzas.ToListAsync(cancellationToken))
Você pode fazer uma projeção antes de acessar o banco
`pizzas.Select(d=> new PizzaDTO(){/* assignments */}).ToListAsync(cancellationToken)` 
o que faz com que o ToListAsync retorne uma list de PizzaDTO e você não precisaria criar/gerenciar essa lista e nem iterar em cima da coleção

2022-02-14 14:54 UTC, patrickhacens approved these changes

2022-02-14 14:54 UTC, merged